### ISSUE TITLE
How to install CVXOPT with MKL in Anaconda?

### ISSUE THREAD

**Issue by SteveDiamond** [cvxopt/cvxopt#57] opened 2016-05-16 22:38 UTC
Anaconda recently changed to have MKL by default. For some reason I can't install CVXOPT with MKL. @bodono did you deal with a similar issue with SCS? I seem to remember that. 

I can disable MKL in Anaconda and then install CVXOPT, but I'd prefer an installation method that doesn't require this.

**Comment by bodono** [comment] 2016-05-17 09:30
I would say this is a bug in anaconda (or possibly numpy / scipy), it might be worth filing it with them.

What error are you getting exactly? For SCS I detected if the install was trying to link against MKL and, if so, looked for a different BLAS / LAPACK install. This is suboptimal because it means that anyone who actually wants to use MKL won't be able to without some code change.

**Comment by SteveDiamond** [comment] 2016-05-17 17:34
It's a little hard to tell where the error is happening. I think ``lapack.sytrf`` is throwing it.

Why can't SCS use MKL?

**Comment by bodono** [comment] 2016-05-18 10:09
So it's not a linking error then, which is a different issue to what SCS was having.

SCS can use MKL. But anaconda is telling packages to link against a missing library, so SCS checks if that library is returned in the `get_info('blas_opt')` (the library in question is `mkl_intel_lp64`) and if so, SCS falls back to using the linkage information from `get_info('blas')`. However if someone is not missing `mkl_intel_lp64` and wants to use it, then they will have to override that behavior. Hopefully this is temporary until the issue is fixed in anaconda or numpy / scipy.

**Comment by martinandersen** [comment] 2016-12-08 10:43
CVXOPT appears to work without any issues when linked against MKL (see our updated [installation instructions](http://cvxopt.org/install/index.html)), so this is most likely an Anaconda issue.

**Closed by martinandersen** 2016-12-08 10:43 UTC
