### ISSUE TITLE
Installation fails under Windows, Python 2.7

### ISSUE THREAD

**Issue by MaxAlex** [cvxopt/cvxopt#118] opened 2018-05-23 17:38 UTC
I'm running Python 2.7 under Windows 7.  I've tried installing via pip and via install from the Github zip file linked to by the documentation.

Attempting to install via ```setup.py install``` (having fully removed the attempted install from pip) fails, showing:
```
C:\Users\Max\Downloads\cvxopt-master\cvxopt-master>python setup.py install
running install
running bdist_egg
running egg_info
creating cvxopt.egg-info
writing cvxopt.egg-info\PKG-INFO
writing top-level names to cvxopt.egg-info\top_level.txt
writing dependency_links to cvxopt.egg-info\dependency_links.txt
writing manifest file 'cvxopt.egg-info\SOURCES.txt'
reading manifest file 'cvxopt.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'cvxopt.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib.win-amd64-2.7
creating build\lib.win-amd64-2.7\cvxopt
copying src\python\coneprog.py -> build\lib.win-amd64-2.7\cvxopt
copying src\python\cvxprog.py -> build\lib.win-amd64-2.7\cvxopt
copying src\python\info.py -> build\lib.win-amd64-2.7\cvxopt
copying src\python\misc.py -> build\lib.win-amd64-2.7\cvxopt
copying src\python\modeling.py -> build\lib.win-amd64-2.7\cvxopt
copying src\python\msk.py -> build\lib.win-amd64-2.7\cvxopt
copying src\python\printing.py -> build\lib.win-amd64-2.7\cvxopt
copying src\python\solvers.py -> build\lib.win-amd64-2.7\cvxopt
copying src\python\_version.py -> build\lib.win-amd64-2.7\cvxopt
copying src\python\__init__.py -> build\lib.win-amd64-2.7\cvxopt
UPDATING build\lib.win-amd64-2.7\cvxopt/_version.py
set build\lib.win-amd64-2.7\cvxopt/_version.py to '1.2.0'
running build_ext
building 'base' extension
creating build\temp.win-amd64-2.7
creating build\temp.win-amd64-2.7\Release
creating build\temp.win-amd64-2.7\Release\src
creating build\temp.win-amd64-2.7\Release\src\C
C:\Users\Max\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo
/Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Python27\PC /Tcsrc/C/base.c /Fobuild\temp.win-amd64-2.7\R
elease\src/C/base.obj
base.c
c:\users\max\downloads\cvxopt-master\cvxopt-master\src\c\cvxopt.h(31) : fatal error C1083: Cannot open include
 file: 'complex.h': No such file or directory
error: command 'C:\\Users\\Max\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\B
in\\amd64\\cl.exe' failed with exit status 2
```

The file "complex.h" does not appear anywhere in the project; I suppose it expects it to be present in MSVC?  Is there particular compiler version (or some extension, etc) required for compilation?

Meanwhile, installation via pip reports "Successfully installed cvxopt-1.2.0"; however, when attempting to subsequently import CXVOPT, it throws an exception:
```
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cvxopt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\cvxopt\__init__.py", line 50, in <module>
    import cvxopt.base
ImportError: DLL load failed: The specified module could not be found.
```
Looking at base.pyd in Dependency Walker, it appears that what it's missing is MKL_RT.dll (several other system .dlls also appear as not found, but I've encountered modules that work fine despite those being "missing."  I don't claim to understand Dependency Walker very well.)

Copying mkl_rt.dll from C:\Python27\Library\bin into the base CVXOPT install directory allows CVXOPT to import without error.

**Comment by martinandersen** [comment] 2018-05-23 19:08
The instructions for building from source with Python 2.7 on Windows are available here:
http://cvxopt.org/install/index.html#windows

I am not exactly sure why the `pip install cvxopt` doesn't work on your system, but an easy fix would be to add "C:\Python27\Library\bin" to your `PATH` since this is where `pip` installs the MKL DLLs.

**Comment by martinandersen** [comment] 2018-07-31 08:50
I'm closing this issue since I cannot reproduce the problem. Feel free to re-open if this is still an issue.

**Closed by martinandersen** 2018-07-31 08:50 UTC
