### ISSUE TITLE
The solver is not stable

### ISSUE THREAD

**Issue by Edenharder** [cvxopt/cvxopt#91] opened 2017-02-27 09:13 UTC
It seems that the solver is not stable, sometimes different runs give different results. Especially when we adjust 'abstol', 'reltol', 'feastol' to smaller numbers and set 'maxiters' to a larger number.

Do the start points rely on time or they are chosen randomly?

**Comment by martinandersen** [comment] 2017-02-27 10:42
What tolerances give rise to this behavior? 

The starting point is deterministic, but it is the result of some computations. What BLAS/LAPACK libraries do you use? Are they multithreaded? Multithreading often lead to non-deterministic behavior.

**Comment by Edenharder** [comment] 2017-02-27 22:57
I use the built-in BLAS/LAPACK libraries. Tolerances are set to 
```
solvers.options['abstol'] = 1e-12
solvers.options['reltol'] = 1e-10
solvers.options['feastol'] = 1e-12
```

It seems that `solvers.options['feastol'] = 1e-12` causes this problem. 

To be honest, I even don't know how to make cvxopt multithreaded.

**Comment by martinandersen** [comment] 2017-02-28 07:04
Those tolerances are very low. What operating system are you using? How did you install CVXOPT? From source? Via pip or conda?

**Comment by Edenharder** [comment] 2017-02-28 07:29
Operating system: MacOS El Capitan 10.11.6
I installed CVXOPT from source with GLPK.

**Comment by martinandersen** [comment] 2017-02-28 07:33
Then you should be able to control the maximum number of threads via the environment variable `VECLIB_MAXIMUM_THREADS`. Try setting this to 1 to see if the non-deterministic behavior persists:

```
export VECLIB_MAXIMUM_THREADS=1
python you_script.py
```

**Comment by Edenharder** [comment] 2017-02-28 07:46
![image](https://cloud.githubusercontent.com/assets/6672134/23396118/50ff8a2a-fd92-11e6-9b06-c1054f057f99.png)
Problem is still there.

**Comment by martinandersen** [comment] 2017-02-28 07:49
OK, we'll need a minimal example in order to figure out why this happens.

**Comment by Edenharder** [comment] 2017-02-28 08:04
```
import numpy as np
from cvxopt import matrix, solvers, sparse, spmatrix

solvers.options['abstol'] = 1e-12
solvers.options['reltol'] = 1e-10
solvers.options['feastol'] = 1e-12
solvers.options['maxiters'] = 1000
solvers.options['show_progress'] = False

def mhcoe(vec):
    dim = len(vec)
    return np.kron(np.sqrt(vec),np.sqrt(vec)).reshape(dim,dim)

edges = [(0,1),(1,2),(2,3),(3,4),(4,0),(0,5),(5,6),(6,7),(7,4)]
wvec = [2., 1, 1, 1, 2, 1, 1, 1]
ne = len(edges)
nv = 1+max([it[1] for it in edges])    
c = matrix([0.0]*ne + [1.0])
G1 = spmatrix(0, [], [], (nv*nv, ne+1))
for (k, (i, j)) in enumerate(edges):
    G1[i*nv+j, k] = 1
    G1[j*nv+i, k] = 1

for i in range(nv):
    G1[i*nv+i, ne] = 1
G1 = -G1
h1 = -matrix(mhcoe(wvec))
sol = solvers.sdp(c, Gs=[G1], hs=[h1])

print sol['dual objective']
```

**Comment by martinandersen** [comment] 2017-02-28 08:19
This is an issue with the built-in BLAS/LAPACK libraries. With these libraries, I can reproduce the non-deterministic behavior, but if I link against single-threaded OpenBLAS, CVXOPT consistently fails after 132 iterations. 

I am closing this issue since it is not a problem specific to CVXOPT.

**Closed by martinandersen** 2017-02-28 08:19 UTC

**Comment by Edenharder** [comment] 2017-02-28 08:29
So, as you said, the built-in BLAS/LAPACK libraries result in non-deterministic behavior while the single-threaded OpenBLAS fails. Which library is better then? Will the Intel MKL library be better?

It seems that one cannot re-link against another library after CVXOPT is installed.

Many thanks!

**Comment by martinandersen** [comment] 2017-02-28 09:39
The problem is essentially that your tolerances are too low: CVXOPT cannot solve your problem to that accuracy. Even in the case where you observe non-deterministic behavior, the solver stops after the maximum number of iterations, and hence does not return the status `'optimal'` (in your example `sol['status']` is `'unknown'`). So non-deterministic or not, this means that the result may be garbage.

If you want to try out a different set of BLAS/LAPACK libraries, you will need to uninstall CVXOPT and rebuild/reinstall it.
