### ISSUE TITLE
Test error when using LAPACK_LIB=openblas

### ISSUE THREAD

**Issue by timokau** [cvxopt/cvxopt#122] opened 2018-07-05 13:34 UTC
Hi!

When using openblas as lapack, I noticed a test error that sometimes occurs. Under normal operation it appears roughly half the time. When the system is under load, it appears nearly every time.

Error:

```
======================================================================
ERROR: test_l1 (test_custom_kkt.TestCustomKKT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/timo/cvxopt/tests/test_custom_kkt.py", line 16, in test_l1
    u1 = l1(P,q)
  File "/home/timo/cvxopt/tests/test_custom_kkt.py", line 126, in l1
    primalstart={'x': x0, 's': s0}, dualstart={'z': z0})
  File "/usr/lib/python2.7/site-packages/cvxopt/coneprog.py", line 1080, in conelp
    raise ValueError("Rank(A) < p or Rank([G; A]) < n")
ValueError: Rank(A) < p or Rank([G; A]) < n

======================================================================
ERROR: test_ch8_l1 (test_examples.TestExamples)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/timo/cvxopt/tests/test_examples.py", line 51, in test_ch8_l1
    gdict = self.exec_example('doc/chap8/l1.py')
  File "/home/timo/cvxopt/tests/test_examples.py", line 14, in exec_example
    exec(code, gdict)
  File "/home/timo/cvxopt/examples/doc/chap8/l1.py", line 126, in <module>
    x, y = l1(P,q)
  File "/home/timo/cvxopt/examples/doc/chap8/l1.py", line 120, in l1
    primalstart={'x': x0, 's': s0}, dualstart={'z': z0})
  File "/usr/lib/python2.7/site-packages/cvxopt/coneprog.py", line 1080, in conelp
    raise ValueError("Rank(A) < p or Rank([G; A]) < n")
ValueError: Rank(A) < p or Rank([G; A]) < n

----------------------------------------------------------------------
Ran 38 tests in 7.601s

FAILED (errors=2, skipped=7)
```

To reproduce, make sure you have openblas with lapack support installed, maybe put your system under load and execute

```
CVXOPT_LAPACK_LIB=openblas python2 -m unittest discover -s tests
```

**Comment by martinandersen** [comment] 2018-07-05 14:02
How did you install CVXOPT? What version? What OS/platform?

**Comment by timokau** [comment] 2018-07-05 19:44
I first encountered the error on nixos, but I reproduced it on a fresh clone of the repo.

**Comment by timokau** [comment] 2018-07-05 19:44
The repo is on tag 1.2.0

**Comment by martinandersen** [comment] 2018-07-06 04:13
How did you install CVXOPT? From source? Using pip? Conda? Which version of OpenBLAS?

**Comment by martinandersen** [comment] 2018-07-06 18:38
This is most likely an openblas problem. Which version of openblas are you linking against? Also, can you reproduce the error with any of our precompiled packages (e.g., "pip install cvxopt" or "conda install -c conda-forge cvxopt")?

**Comment by timokau** [comment] 2018-07-06 19:18
I just tried to work around the problem by switching to liblapack (built with ATLAS) and I'm seeing the same error. I think I was wrong attributing this to openblas. I also encountered two new errors (not all of them occur every time):

```
FAIL: test_ch8_l1 (test_examples.TestExamples)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-python2.7-cvxopt-1.2.0.drv-0/cvxopt-1.2.0/tests/test_examples.py", line 53, in test_ch8_l1
    self.assertAlmostEqualLists(list(P.T*y),P.size[1]*[0.0],5)
  File "/tmp/nix-build-python2.7-cvxopt-1.2.0.drv-0/cvxopt-1.2.0/tests/test_examples.py", line 19, in assertAlmostEqualLists
    for u,v in zip(L1,L2): self.assertAlmostEqual(u,v,places)
AssertionError: -1.2704307514936808 != 0.0 within 5 places
```

and

```
======================================================================
FAIL: test_l1 (test_custom_kkt.TestCustomKKT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-python2.7-cvxopt-1.2.0.drv-0/cvxopt-1.2.0/tests/test_custom_kkt.py", line 18, in test_l1
    self.assertAlmostEqualLists(list(u1),list(u2),places=3)
  File "/tmp/nix-build-python2.7-cvxopt-1.2.0.drv-0/cvxopt-1.2.0/tests/test_custom_kkt.py", line 9, in assertAlmostEqualLists
    for u,v in zip(L1,L2): self.assertAlmostEqual(u,v,places)
AssertionError: 0.01316474861185147 != 0.027780525714296168 within 3 places
```

those are apparently simple imprecisions just outside of the allowance.

I'm currently trying to reproduce with the pip install. No success yet and I already ran it multiple times. I'll keep it running for a while to be sure, but it looks like it does not occur with the pip install.

**Comment by timokau** [comment] 2018-07-06 19:19
Can you reproduce it with the steps I gave?

**Comment by martinandersen** [comment] 2018-07-06 20:28
I now get the same kind of failures after upgrading to OpenBLAS 0.3.1. I'll try to pin down the problem.

**Comment by martinandersen** [comment] 2018-07-06 20:32
The randomness has to do with the fact that the example used in the test generates the problem data  randomly, so it may (simply) be an issue with a poorly scaled problem instance.

**Comment by timokau** [comment] 2018-07-06 20:35
I can confirm that the error doesn't occur with openblas 0.3.0. I assumed it was just due to the non-determinism that the error just started appearing recently, but now it makes sense.

I think it might be a good idea to make the tests as deterministic as possible. Non-deterministic bugs are frustrating to debug.

Thanks for looking into it :)

**Comment by timokau** [comment] 2018-07-06 20:35
I still can't reproduce it with the pip install for some reason.

**Comment by martinandersen** [comment] 2018-07-07 18:28
I'm am convinced that this is an issue with OpenBLAS 0.3.1, and more specifically a call to `dpotrf`. I tried modifying `tests/test_custom_kkt.py` as follows:

```diff
         A = P.T * spdiag(D) * P
-        lapack.potrf(A)
+        try:
+            lapack.potrf(A)
+        except ArithmeticError as E:
+            print("ArithmeticError:")
+            print(E)
+            A = P.T * spdiag(D) * P
+            lapack.potrf(A)
```

The first LAPACK call usually succeeds, but occationally it fails. Here's an example of the output:

```
pcost       dcost       gap    pres   dres   k/t
 0:  2.8235e+02  8.8554e+01  2e+02  6e-17  7e-15  1e+00
 1:  2.6014e+02  1.6612e+02  9e+01  5e-16  1e-11  4e-01
 2:  2.6570e+02  1.8031e+02  9e+01  5e-16  1e-11  3e-01
 3:  2.6999e+02  1.8911e+02  8e+01  6e-16  1e-11  2e-01
ArithmeticError:
132
 4:  2.7001e+02  1.8996e+02  8e+01  7e-16  2e+00  2e-01
 5:  2.5037e+02  2.0331e+02  5e+01  6e-16  1e+00  4e-02
 6:  2.2167e+02  2.1152e+02  1e+01  5e-16  2e-01  9e-03
 7:  2.1664e+02  2.1295e+02  4e+00  4e-16  9e-02  3e-03
 8:  2.1496e+02  2.1342e+02  2e+00  5e-16  4e-02  1e-03
 9:  2.1432e+02  2.1361e+02  7e-01  5e-16  2e-02  7e-04
10:  2.1394e+02  2.1373e+02  2e-01  5e-16  5e-03  2e-04
11:  2.1384e+02  2.1376e+02  8e-02  4e-16  2e-03  8e-05
12:  2.1379e+02  2.1377e+02  2e-02  5e-16  5e-04  2e-05
13:  2.1378e+02  2.1377e+02  9e-03  5e-16  2e-04  9e-06
14:  2.1378e+02  2.1378e+02  1e-03  6e-16  3e-05  1e-06
15:  2.1378e+02  2.1378e+02  2e-04  5e-16  4e-06  2e-07
16:  2.1378e+02  2.1378e+02  2e-06  5e-16  4e-08  2e-09
Optimal solution found.
```

Note that simply retrying the Cholesky factorization works in this case. The error number indicates where the Cholesky factorization fails, and it is not always the same despite the problem instance being the same.

I cannot reproduce the problem with MKL or earlier versions of OpenBLAS.

**Comment by timokau** [comment] 2018-07-08 11:19
Do you understand the problem well enough to file an issue against https://github.com/xianyi/OpenBLAS? Unfortunately I don't know enough about the underlying math or openblas to do it myself.

Also what "quick fix" do you recommend for the nixos package? I could pin openblas to 0.3.0, but that would require building two different versions of openblas and probably bite us some time in the future. Do you think the error is severe enough to warrant that? Or given the nature of the bug, maybe add a patch to the relevant function(s) that simply re-tries on error?

**Comment by martinandersen** [comment] 2018-07-08 19:10
It could be related to this issue: xianyi/OpenBLAS#1673 

> Note 0.3.1 has a known problem with thread allocation that should be fixed in develop.

I'll try with the develop branch tomorrow to see if that fixes the problem.

**Comment by timokau** [comment] 2018-07-08 22:07
Yes, that seems to be it! I (think) I cannot reproduce with https://github.com/xianyi/OpenBLAS/pull/1667 applied. I've proposed that patch for my distro.

For the record: Regardless of the cause of this bug, I think it would be a good idea to un-randomize the tests.

**Comment by timokau** [comment] 2018-07-08 22:07
Thanks for tracking it down :)

**Comment by martinandersen** [comment] 2018-07-09 06:59
OK, I'll go ahead and close this issue since it is not a CVXOPT bug.

On a related note, we are working on more comprehensive tests. Many of our current tests involve running some of our examples (some of which are based on random data). This is really just a stopgap solution until we have some more systematic tests in place.

**Closed by martinandersen** 2018-07-09 06:59 UTC

**Comment by martinandersen** [comment] 2018-07-30 21:14
OpenBLAS 0.3.2 has now been released — it appears to fix this issue.
